export type ItemType = 'folder' | 'button';

export interface Item {
  id: string;
  type: ItemType;
  label: string;
  emoji?: string;
  backgroundColor: string;
  textColor: string;
  /** null means the item lives at the root (home screen) */
  folderId: string | null;
  order: number;
}

/** Semantic alias – a button-type Item is the "word" the user speaks */
export type Word = Item & { type: 'button' };

/** Semantic alias – a folder-type Item is a navigable category */
export type Folder = Item & { type: 'folder' };

/** Payload for creating a new item (id is generated by the store) */
export type CreateItemPayload = Omit<Item, 'id'>;

/** Payload for updating an existing item (all fields except id are optional) */
export type UpdateItemPayload = Pick<Item, 'id'> & Partial<Omit<Item, 'id'>>;
