import type { Item } from './item.model';

/**
 * Raw seed entries. Buttons have `id: null` intentionally – the store
 * will call crypto.randomUUID() before persisting them to IndexedDB.
 */
type RawSeedItem = Omit<Item, 'id'> & { id: string | null };

const RAW_DEFAULT_ITEMS: RawSeedItem[] = [
  // Categories
  {
    id: 'folder-core',
    type: 'folder',
    label: 'Palabras Clave',
    emoji: '🔑',
    backgroundColor: '#3b82f6',
    textColor: '#111827',
    folderId: null,
    order: 0,
  },
  {
    id: 'folder-feelings',
    type: 'folder',
    label: 'Sentimientos',
    emoji: '😊',
    backgroundColor: '#ef4444',
    textColor: '#111827',
    folderId: null,
    order: 1,
  },
  {
    id: 'folder-actions',
    type: 'folder',
    label: 'Acciones',
    emoji: '🏃',
    backgroundColor: '#6b7280',
    textColor: '#111827',
    folderId: null,
    order: 2,
  },
  {
    id: 'folder-food',
    type: 'folder',
    label: 'Comida y Bebida',
    emoji: '🍎',
    backgroundColor: '#22c55e',
    textColor: '#111827',
    folderId: null,
    order: 3,
  },
  {
    id: 'folder-people',
    type: 'folder',
    label: 'Personas',
    emoji: '👥',
    backgroundColor: '#f59e0b',
    textColor: '#111827',
    folderId: null,
    order: 4,
  },
  {
    id: 'folder-places',
    type: 'folder',
    label: 'Lugares',
    emoji: '🏠',
    backgroundColor: '#ec4899',
    textColor: '#111827',
    folderId: null,
    order: 5,
  },
  {
    id: 'folder-questions',
    type: 'folder',
    label: 'Preguntas',
    emoji: '❓',
    backgroundColor: '#14b8a6',
    textColor: '#111827',
    folderId: null,
    order: 6,
  },
  {
    id: 'folder-social',
    type: 'folder',
    label: 'Social',
    emoji: '💬',
    backgroundColor: '#6366f1',
    textColor: '#111827',
    folderId: null,
    order: 7,
  },



  // Core Words
  {
    id: null,
    type: 'button',
    label: 'Yo',
    emoji: '🙋',
    backgroundColor: '#3b82f6',
    textColor: '#1f2937',
    folderId: 'folder-core',
    order: 0,
  },
  {
    id: null,
    type: 'button',
    label: 'Tú',
    emoji: '👉',
    backgroundColor: '#ef4444',
    textColor: '#1f2937',
    folderId: 'folder-core',
    order: 1,
  },
  {
    id: null,
    type: 'button',
    label: 'Él',
    emoji: '👦',
    backgroundColor: '#6b7280',
    textColor: '#1f2937',
    folderId: 'folder-core',
    order: 2,
  },
  {
    id: null,
    type: 'button',
    label: 'Ella',
    emoji: '👧',
    backgroundColor: '#22c55e',
    textColor: '#1f2937',
    folderId: 'folder-core',
    order: 3,
  },
  {
    id: null,
    type: 'button',
    label: 'Esto',
    emoji: '👇',
    backgroundColor: '#f59e0b',
    textColor: '#1f2937',
    folderId: 'folder-core',
    order: 4,
  },
  {
    id: null,
    type: 'button',
    label: 'Eso',
    emoji: '👆',
    backgroundColor: '#ec4899',
    textColor: '#1f2937',
    folderId: 'folder-core',
    order: 5,
  },
  {
    id: null,
    type: 'button',
    label: 'Aquí',
    emoji: '📍',
    backgroundColor: '#14b8a6',
    textColor: '#1f2937',
    folderId: 'folder-core',
    order: 6,
  },
  {
    id: null,
    type: 'button',
    label: 'Allí',
    emoji: '🗺️',
    backgroundColor: '#6366f1',
    textColor: '#1f2937',
    folderId: 'folder-core',
    order: 7,
  },

  // Feelings
  {
    id: null,
    type: 'button',
    label: 'Feliz',
    emoji: '😀',
    backgroundColor: '#3b82f6',
    textColor: '#1f2937',
    folderId: 'folder-feelings',
    order: 0,
  },
  {
    id: null,
    type: 'button',
    label: 'Triste',
    emoji: '😢',
    backgroundColor: '#ef4444',
    textColor: '#1f2937',
    folderId: 'folder-feelings',
    order: 1,
  },
  {
    id: null,
    type: 'button',
    label: 'Enojado',
    emoji: '😠',
    backgroundColor: '#6b7280',
    textColor: '#1f2937',
    folderId: 'folder-feelings',
    order: 2,
  },
  {
    id: null,
    type: 'button',
    label: 'Cansado',
    emoji: '🥱',
    backgroundColor: '#22c55e',
    textColor: '#1f2937',
    folderId: 'folder-feelings',
    order: 3,
  },
  {
    id: null,
    type: 'button',
    label: 'Asustado',
    emoji: '😨',
    backgroundColor: '#f59e0b',
    textColor: '#1f2937',
    folderId: 'folder-feelings',
    order: 4,
  },
  {
    id: null,
    type: 'button',
    label: 'Enfermo',
    emoji: '🤒',
    backgroundColor: '#ec4899',
    textColor: '#1f2937',
    folderId: 'folder-feelings',
    order: 5,
  },
  {
    id: null,
    type: 'button',
    label: 'Hambriento',
    emoji: '🤤',
    backgroundColor: '#14b8a6',
    textColor: '#1f2937',
    folderId: 'folder-feelings',
    order: 6,
  },
  {
    id: null,
    type: 'button',
    label: 'Sediento',
    emoji: '🥤',
    backgroundColor: '#6366f1',
    textColor: '#1f2937',
    folderId: 'folder-feelings',
    order: 7,
  },

  // Actions
  {
    id: null,
    type: 'button',
    label: 'Ir',
    emoji: '🚶',
    backgroundColor: '#8b5cf6',
    textColor: '#1f2937',
    folderId: 'folder-actions',
    order: 0,
  },
  {
    id: null,
    type: 'button',
    label: 'Parar',
    emoji: '🛑',
    backgroundColor: '#f5f5f5',
    textColor: '#1f2937',
    folderId: 'folder-actions',
    order: 1,
  },
  {
    id: null,
    type: 'button',
    label: 'Querer',
    emoji: '🤲',
    backgroundColor: '#3b82f6',
    textColor: '#1f2937',
    folderId: 'folder-actions',
    order: 2,
  },
  {
    id: null,
    type: 'button',
    label: 'Tener',
    emoji: '👐',
    backgroundColor: '#ef4444',
    textColor: '#1f2937',
    folderId: 'folder-actions',
    order: 3,
  },
  {
    id: null,
    type: 'button',
    label: 'Mirar',
    emoji: '👀',
    backgroundColor: '#6b7280',
    textColor: '#1f2937',
    folderId: 'folder-actions',
    order: 4,
  },
  {
    id: null,
    type: 'button',
    label: 'Jugar',
    emoji: '🎮',
    backgroundColor: '#22c55e',
    textColor: '#1f2937',
    folderId: 'folder-actions',
    order: 5,
  },
  {
    id: null,
    type: 'button',
    label: 'Comer',
    emoji: '🍽️',
    backgroundColor: '#f59e0b',
    textColor: '#1f2937',
    folderId: 'folder-actions',
    order: 6,
  },
  {
    id: null,
    type: 'button',
    label: 'Beber',
    emoji: '🥛',
    backgroundColor: '#ec4899',
    textColor: '#1f2937',
    folderId: 'folder-actions',
    order: 7,
  },
  {
    id: null,
    type: 'button',
    label: 'Dormir',
    emoji: '🛌',
    backgroundColor: '#14b8a6',
    textColor: '#1f2937',
    folderId: 'folder-actions',
    order: 8,
  },
  {
    id: null,
    type: 'button',
    label: 'Gustar',
    emoji: '👍',
    backgroundColor: '#6366f1',
    textColor: '#1f2937',
    folderId: 'folder-actions',
    order: 9,
  },

  // Food
  {
    id: null,
    type: 'button',
    label: 'Agua',
    emoji: '💧',
    backgroundColor: '#3b82f6',
    textColor: '#1f2937',
    folderId: 'folder-food',
    order: 0,
  },
  {
    id: null,
    type: 'button',
    label: 'Jugo',
    emoji: '🧃',
    backgroundColor: '#ef4444',
    textColor: '#1f2937',
    folderId: 'folder-food',
    order: 1,
  },
  {
    id: null,
    type: 'button',
    label: 'Leche',
    emoji: '🥛',
    backgroundColor: '#6b7280',
    textColor: '#1f2937',
    folderId: 'folder-food',
    order: 2,
  },
  {
    id: null,
    type: 'button',
    label: 'Manzana',
    emoji: '🍎',
    backgroundColor: '#22c55e',
    textColor: '#1f2937',
    folderId: 'folder-food',
    order: 3,
  },
  {
    id: null,
    type: 'button',
    label: 'Plátano',
    emoji: '🍌',
    backgroundColor: '#f59e0b',
    textColor: '#1f2937',
    folderId: 'folder-food',
    order: 4,
  },
  {
    id: null,
    type: 'button',
    label: 'Galleta',
    emoji: '🍪',
    backgroundColor: '#ec4899',
    textColor: '#1f2937',
    folderId: 'folder-food',
    order: 5,
  },
  {
    id: null,
    type: 'button',
    label: 'Pan',
    emoji: '🍞',
    backgroundColor: '#14b8a6',
    textColor: '#1f2937',
    folderId: 'folder-food',
    order: 6,
  },
  {
    id: null,
    type: 'button',
    label: 'Carne',
    emoji: '🥩',
    backgroundColor: '#6366f1',
    textColor: '#1f2937',
    folderId: 'folder-food',
    order: 7,
  },

  // People
  {
    id: null,
    type: 'button',
    label: 'Mamá',
    emoji: '👩',
    backgroundColor: '#3b82f6',
    textColor: '#1f2937',
    folderId: 'folder-people',
    order: 0,
  },
  {
    id: null,
    type: 'button',
    label: 'Papá',
    emoji: '👨',
    backgroundColor: '#ef4444',
    textColor: '#1f2937',
    folderId: 'folder-people',
    order: 1,
  },
  {
    id: null,
    type: 'button',
    label: 'Hermano',
    emoji: '👦',
    backgroundColor: '#6b7280',
    textColor: '#1f2937',
    folderId: 'folder-people',
    order: 2,
  },
  {
    id: null,
    type: 'button',
    label: 'Hermana',
    emoji: '👧',
    backgroundColor: '#22c55e',
    textColor: '#1f2937',
    folderId: 'folder-people',
    order: 3,
  },
  {
    id: null,
    type: 'button',
    label: 'Abuela',
    emoji: '👵',
    backgroundColor: '#f59e0b',
    textColor: '#1f2937',
    folderId: 'folder-people',
    order: 4,
  },
  {
    id: null,
    type: 'button',
    label: 'Abuelo',
    emoji: '👴',
    backgroundColor: '#ec4899',
    textColor: '#1f2937',
    folderId: 'folder-people',
    order: 5,
  },
  {
    id: null,
    type: 'button',
    label: 'Amigo',
    emoji: '🧑‍🤝‍🧑',
    backgroundColor: '#14b8a6',
    textColor: '#1f2937',
    folderId: 'folder-people',
    order: 6,
  },
  {
    id: null,
    type: 'button',
    label: 'Maestro',
    emoji: '👨‍🏫',
    backgroundColor: '#6366f1',
    textColor: '#1f2937',
    folderId: 'folder-people',
    order: 7,
  },

  // Places
  {
    id: null,
    type: 'button',
    label: 'Casa',
    emoji: '🏠',
    backgroundColor: '#3b82f6',
    textColor: '#1f2937',
    folderId: 'folder-places',
    order: 0,
  },
  {
    id: null,
    type: 'button',
    label: 'Escuela',
    emoji: '🏫',
    backgroundColor: '#ef4444',
    textColor: '#1f2937',
    folderId: 'folder-places',
    order: 1,
  },
  {
    id: null,
    type: 'button',
    label: 'Parque',
    emoji: '🏞️',
    backgroundColor: '#6b7280',
    textColor: '#1f2937',
    folderId: 'folder-places',
    order: 2,
  },
  {
    id: null,
    type: 'button',
    label: 'Tienda',
    emoji: '🏪',
    backgroundColor: '#22c55e',
    textColor: '#1f2937',
    folderId: 'folder-places',
    order: 3,
  },
  {
    id: null,
    type: 'button',
    label: 'Baño',
    emoji: '🚽',
    backgroundColor: '#f59e0b',
    textColor: '#1f2937',
    folderId: 'folder-places',
    order: 4,
  },
  {
    id: null,
    type: 'button',
    label: 'Cama',
    emoji: '🛏️',
    backgroundColor: '#ec4899',
    textColor: '#1f2937',
    folderId: 'folder-places',
    order: 5,
  },
  {
    id: null,
    type: 'button',
    label: 'Afuera',
    emoji: '🌳',
    backgroundColor: '#14b8a6',
    textColor: '#1f2937',
    folderId: 'folder-places',
    order: 6,
  },
  {
    id: null,
    type: 'button',
    label: 'Adentro',
    emoji: '🛋️',
    backgroundColor: '#6366f1',
    textColor: '#1f2937',
    folderId: 'folder-places',
    order: 7,
  },

  // Questions
  {
    id: null,
    type: 'button',
    label: 'Qué',
    emoji: '🤷',
    backgroundColor: '#3b82f6',
    textColor: '#1f2937',
    folderId: 'folder-questions',
    order: 0,
  },
  {
    id: null,
    type: 'button',
    label: 'Quién',
    emoji: '👤',
    backgroundColor: '#ef4444',
    textColor: '#1f2937',
    folderId: 'folder-questions',
    order: 1,
  },
  {
    id: null,
    type: 'button',
    label: 'Dónde',
    emoji: '🔍',
    backgroundColor: '#6b7280',
    textColor: '#1f2937',
    folderId: 'folder-questions',
    order: 2,
  },
  {
    id: null,
    type: 'button',
    label: 'Cuándo',
    emoji: '⏰',
    backgroundColor: '#22c55e',
    textColor: '#1f2937',
    folderId: 'folder-questions',
    order: 3,
  },
  {
    id: null,
    type: 'button',
    label: 'Por qué',
    emoji: '🤔',
    backgroundColor: '#f59e0b',
    textColor: '#1f2937',
    folderId: 'folder-questions',
    order: 4,
  },
  {
    id: null,
    type: 'button',
    label: 'Cómo',
    emoji: '🛠️',
    backgroundColor: '#ec4899',
    textColor: '#1f2937',
    folderId: 'folder-questions',
    order: 5,
  },

  // Social
  {
    id: null,
    type: 'button',
    label: 'Por favor',
    emoji: '🙏',
    backgroundColor: '#3b82f6',
    textColor: '#1f2937',
    folderId: 'folder-social',
    order: 0,
  },
  {
    id: null,
    type: 'button',
    label: 'Gracias',
    emoji: '💖',
    backgroundColor: '#ef4444',
    textColor: '#1f2937',
    folderId: 'folder-social',
    order: 1,
  },
  {
    id: null,
    type: 'button',
    label: 'De nada',
    emoji: '😊',
    backgroundColor: '#6b7280',
    textColor: '#1f2937',
    folderId: 'folder-social',
    order: 2,
  },
  {
    id: null,
    type: 'button',
    label: 'Perdón',
    emoji: '😔',
    backgroundColor: '#22c55e',
    textColor: '#1f2937',
    folderId: 'folder-social',
    order: 3,
  },
  {
    id: null,
    type: 'button',
    label: 'Te amo',
    emoji: '❤️',
    backgroundColor: '#f59e0b',
    textColor: '#1f2937',
    folderId: 'folder-social',
    order: 4,
  },
  {
    id: null,
    type: 'button',
    label: 'Adiós',
    emoji: '👋',
    backgroundColor: '#ec4899',
    textColor: '#1f2937',
    folderId: 'folder-social',
    order: 5,
  },
  {
    id: null,
    type: 'button',
    label: 'Bien',
    emoji: '👍',
    backgroundColor: '#14b8a6',
    textColor: '#1f2937',
    folderId: 'folder-social',
    order: 6,
  },
  {
    id: null,
    type: 'button',
    label: 'Mal',
    emoji: '👎',
    backgroundColor: '#6366f1',
    textColor: '#1f2937',
    folderId: 'folder-social',
    order: 7,
  },
];

/**
 * Produces the full default dataset with all IDs resolved.
 * Folders keep their deterministic id; buttons get a fresh UUID each call.
 */
export function buildDefaultItems(): Item[] {
  return RAW_DEFAULT_ITEMS.map(raw => ({
    ...raw,
    id: raw.id ?? crypto.randomUUID(),
  }));
}
