export interface Preference {
  id: string;
  buttonWidth: number;
  buttonHeight: number;
  buttonBorderRadius: number;
  buttonFontSize: number;
  gridGap: number;
  gridPadding: number;
  stretchToFill: boolean;
}


/** Payload for creating a new preference (id is generated by the store) */
export type CreatePreferencePayload = Omit<Preference, 'id'>;

/** Payload for updating an existing preference (all fields except id are optional) */
export type UpdatePreferencePayload = Pick<Preference, 'id'> & Partial<Omit<Preference, 'id'>>;
